# Generated by Django 4.0.6 on 2022-07-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
